# Generated by Django 4.2.1 on 2023-10-15 08:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_culturel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSubmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL where this event can be found.', max_length=512, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Event submission form',
                'verbose_name_plural': 'Event submissions forms',
                'db_table': 'eventsubmissionform',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='reference_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=512), blank=True, help_text='List of all the urls where this event can be found.', null=True, size=None, verbose_name='URLs'),
        ),
    ]
