# Generated by Django 4.2.1 on 2023-10-21 14:59

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_culturel', '0002_eventsubmissionform_alter_event_reference_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=512, verbose_name='Name')),
                ('codename', models.CharField(help_text='Short name of the category', max_length=3, verbose_name='Short name')),
                ('color', colorfield.fields.ColorField(default='#CCCCCCC', help_text='Color used as background for the category', image_field=None, max_length=25, samples=None, verbose_name='Color')),
            ],
        ),
    ]
