# Generated by Django 4.2.1 on 2023-10-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_culturel', '0004_alter_category_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
