# Generated by Django 4.2.1 on 2023-10-29 13:51

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_culturel', '0007_event_category_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reference_urls',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(max_length=512), blank=True, help_text='List of all the urls where this event can be found.', null=True, size=None, verbose_name='URLs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, help_text='A list of tags that describe the event.', null=True, size=None, verbose_name='Tags'),
        ),
    ]
