# Generated by Django 4.2.1 on 2023-10-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_culturel', '0008_alter_event_reference_urls_alter_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='plural',
            field=models.CharField(default='1', help_text='Category name (plural)', max_length=512, verbose_name='Plural nName'),
            preserve_default=False,
        ),
    ]
