# Generated by Django 4.2.1 on 2023-10-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_culturel', '0009_category_plural'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='plural',
        ),
        migrations.AddField(
            model_name='category',
            name='alt_name',
            field=models.CharField(default='1', help_text='Alternative name used with a time period', max_length=512, verbose_name='Alternative Name'),
            preserve_default=False,
        ),
    ]
