# Generated by Django 4.2.1 on 2023-11-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_culturel', '0012_staticcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='url_path',
            field=models.CharField(default='', help_text='URL path where the content is included.', verbose_name='URL path'),
            preserve_default=False,
        ),
    ]
