# Generated by Django 4.2.1 on 2023-11-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_culturel', '0014_alter_event_image_alter_event_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='local_image',
            field=models.URLField(blank=True, help_text='Illustration image stored in the agenda server', max_length=1024, null=True, verbose_name='Illustration (local image)'),
        ),
    ]
