# Generated by Django 4.2.1 on 2023-11-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_culturel', '0015_event_local_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='local_image',
            field=models.ImageField(blank=True, help_text='Illustration image stored in the agenda server', max_length=1024, null=True, upload_to='', verbose_name='Illustration (local image)'),
        ),
    ]
